/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MinerGame;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author İbrahim
 */
public class anaEkran extends javax.swing.JFrame {

    // Variables declaration - do not modify                     
    private javax.swing.JLabel aMaliyetF;
    private javax.swing.JTextField aMaliyetT;
    private javax.swing.JLabel bMaliyetF;
    private javax.swing.JTextField bMaliyetT;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel cMaliyetF;
    private javax.swing.JTextField cMaliyetT;
    private javax.swing.JLabel dMaliyetF;
    private javax.swing.JTextField dMaliyetT;
    private javax.swing.JLabel gizliOranF;
    private javax.swing.JTextField gizliOranT;
    private javax.swing.JTextField heightF;
    private javax.swing.JLabel heightT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel oranF;
    private javax.swing.JTextField oranT;
    private javax.swing.JLabel toplamMaliyetF;
    private javax.swing.JTextField toplamMaliyetT;
    private javax.swing.JLabel widthF;
    private javax.swing.JTextField widthT;
    // End of variables declaration                   

    /**
     * Creates new form anaEkran
     */
    public static int board_boy = 20;
    public static int board_genislik = 20;
    public static int oran = 20;
    public static int gizli_oran = 10;
    public static int aMaliyet;
    public static int aHedef = 5;
    public static int bMaliyet;
    public static int bHedef = 10;
    public static int cMaliyet;
    public static int cHedef = 15;
    public static int cGizli_altin_say = 1;
    public static int dMaliyet = 5;

    public static int toplamMaliyet;
    public static int oyuncu_altin = 200;
    public static int oyuncu_adim_sayisi = 3;
    public static int dHedef = 20;

    public static JButton butonlar[][]; //map oluştuktan sonra ma

    private JTextField baslangic_altin;
    private JLabel baslangic_altinL;
    private JLabel adim_sayisiL;
    private JTextField adim_sayisi;

    public anaEkran() {

        setup();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    public void setup() {

        jPanel1 = new javax.swing.JPanel();
        heightF = new javax.swing.JTextField();
        heightT = new javax.swing.JLabel();
        widthF = new javax.swing.JLabel();
        widthT = new javax.swing.JTextField();
        oranF = new javax.swing.JLabel();
        oranT = new javax.swing.JTextField();
        gizliOranF = new javax.swing.JLabel();
        gizliOranT = new javax.swing.JTextField();
        aMaliyetF = new javax.swing.JLabel();
        aMaliyetT = new javax.swing.JTextField();
        bMaliyetF = new javax.swing.JLabel();
        bMaliyetT = new javax.swing.JTextField();
        cMaliyetF = new javax.swing.JLabel();
        cMaliyetT = new javax.swing.JTextField();
        JTextField cGizli_altin = new javax.swing.JTextField();
        JLabel cGizli_altinL = new JLabel("C Oyuncusu Açılacak Gizli Altın");
        dMaliyetF = new javax.swing.JLabel();
        dMaliyetT = new javax.swing.JTextField();
        toplamMaliyetF = new javax.swing.JLabel();
        toplamMaliyetT = new javax.swing.JTextField();
        backgroundLabel = new javax.swing.JLabel();
        JButton default_ayarlar_ile_basla = new javax.swing.JButton("Varsayilan olarak basla");
        JButton kaydet_ve_oyna = new javax.swing.JButton("kaydet ve oyna");
        adim_sayisi = new javax.swing.JTextField();
        adim_sayisiL = new javax.swing.JLabel("Oyuncu Adım Sayısı");
        baslangic_altin = new javax.swing.JTextField();
        baslangic_altinL = new javax.swing.JLabel("Oyuncu Başlangıc Altınları");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel1.add(heightF);
        heightF.setBounds(80, 170, 40, 30);
        kaydet_ve_oyna.setBounds(250, 520, 350, 30);
        adim_sayisi.setBounds(230, 170, 40, 30);

        adim_sayisiL.setBounds(200, 140, 140, 20);
        adim_sayisiL.setForeground(Color.YELLOW);
        jPanel1.add(adim_sayisi);
        jPanel1.add(adim_sayisiL);
        baslangic_altinL.setBounds(200, 230, 210, 30);
        baslangic_altinL.setForeground(Color.yellow);
        baslangic_altin.setBounds(230, 260, 40, 30);
        jPanel1.add(baslangic_altinL);
        jPanel1.add(baslangic_altin);

        jPanel1.add(kaydet_ve_oyna);
        heightT.setForeground(new java.awt.Color(255, 255, 102));
        heightT.setText("Oyun Tahtası Yükseklik");
        jPanel1.add(heightT);
        heightT.setBounds(40, 140, 140, 20);
        default_ayarlar_ile_basla.setBounds(213, 550, 450, 30);
        jPanel1.add(default_ayarlar_ile_basla);
        widthF.setForeground(new java.awt.Color(255, 255, 102));
        widthF.setText("Oyun Tahtası Genişliği");
        jPanel1.add(widthF);
        widthF.setBounds(40, 230, 130, 30);
        cGizli_altinL.setBounds(720, 280, 170, 20);
        cGizli_altinL.setForeground(Color.yellow);
        cGizli_altin.setBounds(770, 310, 40, 30);
        jPanel1.add(cGizli_altinL);
        jPanel1.add(cGizli_altin);
        jPanel1.add(widthT);
        widthT.setBounds(80, 260, 40, 30);

        oranF.setForeground(new java.awt.Color(255, 255, 102));
        oranF.setText("Altın Bulunma Oranı (%)");
        jPanel1.add(oranF);
        oranF.setBounds(50, 310, 140, 30);

        jPanel1.add(oranT);
        oranT.setBounds(80, 340, 40, 30);

        gizliOranF.setForeground(new java.awt.Color(255, 255, 102));
        gizliOranF.setText("Gizli Altın Bulunma Oranı (%)");
        jPanel1.add(gizliOranF);
        gizliOranF.setBounds(200, 430, 170, 30);

        jPanel1.add(gizliOranT);
        gizliOranT.setBounds(250, 460, 40, 30);

        aMaliyetF.setForeground(new java.awt.Color(255, 255, 102));
        aMaliyetF.setText("A Oyuncusu Hedef Belirleme Maliyeti");
        jPanel1.add(aMaliyetF);
        aMaliyetF.setBounds(510, 130, 220, 30);

        jPanel1.add(aMaliyetT);
        aMaliyetT.setBounds(590, 160, 40, 30);

        bMaliyetF.setForeground(new java.awt.Color(255, 255, 102));
        bMaliyetF.setText("B Oyuncusu Hedef Belirleme Maliyeti");
        jPanel1.add(bMaliyetF);
        bMaliyetF.setBounds(510, 200, 220, 30);

        jPanel1.add(bMaliyetT);
        bMaliyetT.setBounds(590, 230, 40, 30);

        cMaliyetF.setForeground(new java.awt.Color(255, 255, 102));
        cMaliyetF.setText("C Oyuncusu Hedef Belirleme Maliyeti");
        jPanel1.add(cMaliyetF);
        cMaliyetF.setBounds(500, 280, 220, 30);

        jPanel1.add(cMaliyetT);
        cMaliyetT.setBounds(590, 310, 40, 30);

        dMaliyetF.setForeground(new java.awt.Color(255, 255, 102));
        dMaliyetF.setText("D Oyuncusu Hedef Belirleme Maliyeti");
        jPanel1.add(dMaliyetF);
        dMaliyetF.setBounds(510, 360, 230, 16);

        jPanel1.add(dMaliyetT);
        dMaliyetT.setBounds(590, 390, 40, 24);

        toplamMaliyetF.setForeground(new java.awt.Color(255, 255, 102));
        toplamMaliyetF.setText("Toplam Adım Maliyeti");
        jPanel1.add(toplamMaliyetF);
        toplamMaliyetF.setBounds(550, 430, 130, 16);

        jPanel1.add(toplamMaliyetT);
        toplamMaliyetT.setBounds(590, 460, 40, 24);
        
        ImageIcon ıcon = new ImageIcon("gold-catcher-background.jpg");
        backgroundLabel.setIcon(ıcon);
        jPanel1.add(backgroundLabel);

        backgroundLabel.setBounds(0, -230, 1910, 1070);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        kaydet_ve_oyna.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ayarlar_okuma();
            }
        });
        default_ayarlar_ile_basla.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                default_basla();
            }

        });

        pack();
// </editor-fold>                        
    }

    public void default_basla() {
        this.board_boy = 20;
        this.board_genislik = 20;
        this.oran = 20;
        this.gizli_oran = 10;
        this.aMaliyet = 5;
        this.aHedef = 5;
        this.bMaliyet = 5;
        this.bHedef = 10;
        this.cMaliyet = 5;
        this.cHedef = 15;
        this.cGizli_altin_say = 1;
        this.dMaliyet = 5;
        this.dHedef = 20;
        this.oyuncu_adim_sayisi = 3;
        this.oyuncu_altin = 200;
        //this.toplamMaliyet;
        oyun_ekranı();

    }

    public void ayarlar_okuma() throws NumberFormatException {

        try {
            this.board_boy = Integer.parseInt(heightF.getText());
        } catch (Exception e) {
            this.board_boy = 20;

        }

        try {
            this.board_genislik = Integer.parseInt(widthT.getText());
        } catch (Exception e) {
            this.board_genislik = 20;
        }

        try {
            this.oran = Integer.parseInt(oranT.getText());
        } catch (Exception e) {
            this.oran = 20;
        }

        try {
            this.gizli_oran = Integer.parseInt(gizliOranT.getText());
        } catch (Exception e) {

            this.gizli_oran = 10;
        }

        try {
            this.aMaliyet = Integer.parseInt(aMaliyetT.getText());
        } catch (Exception e) {
            this.aMaliyet = 5;
        }

        try {
            this.bMaliyet = Integer.parseInt(bMaliyetT.getText());
        } catch (Exception e) {
            this.bMaliyet = 5;
        }

        try {
            this.cMaliyet = Integer.parseInt(cMaliyetT.getText());
        } catch (Exception e) {
            this.cMaliyet = 5;
        }

        try {
            this.dMaliyet = Integer.parseInt(dMaliyetT.getText());
        } catch (Exception e) {
            this.dMaliyet = 5;
        }

        try {
            this.toplamMaliyet = Integer.parseInt(toplamMaliyetT.getText());
        } catch (Exception e) {
        }

        try {
            this.oyuncu_altin = Integer.parseInt(baslangic_altin.getText());
        } catch (Exception e) {
            this.oyuncu_altin = 200;
        }

        try {
            this.oyuncu_adim_sayisi = Integer.parseInt(adim_sayisi.getText());
        } catch (Exception e) {
            this.oyuncu_adim_sayisi = 3;
        }

        oyun_ekranı();

    }

    public void kurulum() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anaEkran.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anaEkran.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anaEkran.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anaEkran.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anaEkran().setVisible(true);
            }
        });
    }

    public void oyun_ekranı() {

        Random random = new Random();
        JFrame frame2 = new JFrame(" Grid Layout");
        frame2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        int boy = this.board_boy;
        int genislik = this.board_genislik;
        JPanel p1 = new JPanel(new GridLayout(boy, genislik));

        JButton butonlar[][] = new JButton[boy][genislik];

        for (int i = 0; i < boy; i++) {
            for (int j = 0; j < genislik; j++) {
                butonlar[i][j] = new JButton();

                p1.add(butonlar[i][j]);
            }
        }

        butonlar[0][0].setText("A");
        butonlar[0][0].setForeground(Color.WHITE);
        butonlar[0][0].setBackground(Color.BLUE);
        butonlar[0][genislik - 1].setText("B");
        butonlar[0][genislik - 1].setForeground(Color.WHITE);
        butonlar[0][genislik - 1].setBackground(Color.BLUE);
        butonlar[boy - 1][0].setText("C");
        butonlar[boy - 1][0].setForeground(Color.WHITE);
        butonlar[boy - 1][0].setBackground(Color.BLUE);
        butonlar[boy - 1][genislik - 1].setText("D");
        butonlar[boy - 1][genislik - 1].setForeground(Color.WHITE);
        butonlar[boy - 1][genislik - 1].setBackground(Color.BLUE);

        int tempA;
        int tempx;
        int tempy;
        int konulcak_altin_say = ((this.board_boy * this.board_genislik) * this.oran) / 100;
        int konulan_altin_say = 0;
        if (konulcak_altin_say < 1) {
            konulcak_altin_say = 1;
        }

        int i = 0;
        while (konulan_altin_say < konulcak_altin_say) // 80 kısmı satirxsutun %20 si seklinde alinacak.    //80den az üretme fixlendi // yeteri kadar altın üretmeden döngü bitmesin
        {

            tempx = random.nextInt(boy);
            tempy = random.nextInt(genislik);

            if ((butonlar[tempx][tempy].getBackground() != Color.BLUE) && (butonlar[tempx][tempy].getBackground() != Color.YELLOW)) {   //aynı yere 2 defa altın koyma fixlendi

                tempA = ((random.nextInt(20 / 5) * 5)) + 5;
                butonlar[tempx][tempy].setText(tempA + "");
                butonlar[tempx][tempy].setBackground(Color.YELLOW);
                konulan_altin_say++;  // altin ürettiysek bu artar 

            }

        }

        int tempx2;
        int tempy2;
        int kontrol = 0;
        int konulcak_gizli_altin = (konulcak_altin_say * this.gizli_oran) / 100;
        if (konulcak_gizli_altin < 1) {

            konulcak_gizli_altin = 1;
        }
        while (kontrol <= konulcak_gizli_altin) // altin olan kutularin %10'u kadar gizli altin kutusu --> 8 gecici deger
        {

            tempx2 = random.nextInt(boy);
            tempy2 = random.nextInt(genislik);
            String kutu = butonlar[tempx2][tempy2].getText();
            if (!(kutu.equalsIgnoreCase("")) && (butonlar[tempx2][tempy2].getBackground() == Color.yellow)) // A B C D oyuncularının başlangıç konumlarına gizli altın ataması yapması engellenecek.  //A B C D'de gizli altın koymuyoruz
            {

                butonlar[tempx2][tempy2].setBackground(Color.GRAY);
                butonlar[tempx2][tempy2].setForeground(Color.RED);
                kontrol++;

            }

        }

        frame2.add(p1, BorderLayout.NORTH);

        this.butonlar = butonlar;   // Diğer klaslarda kullanabilmek için butonları klassın altına aktardık.
        frame2.pack();
        frame2.setVisible(true);
    }
}
